const catchAsync = fn => (req, res, next) => {
  fn(req, res, next).catch(e => {
    global.logger.error('ðŸ”¥ error: %o', e);
    return next(e);
  });
};

export default catchAsync;